/**
 * tools.define / tools.compile — freeze explored flows into first-class tools.
 * A defined tool is a plain OpenCLI adapter module written to ~/.opencli-mcp/tools/<site>/<name>.js,
 * registered live (tools/list_changed), and reloaded on the next start. Three sources share one
 * registry: built-in adapters, agent-defined tools, page-provided (WebMCP) tools.
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { DEFINED_TOOLS_DIR } from './registry.js';
import { getRegistry } from '@jackwener/opencli/registry';
import { opencliRoot } from '../lib/opencli.js';
import type { TraceEvent } from '../runtime/trace.js';

export interface ArgDef { name: string; type?: 'string' | 'int' | 'number' | 'boolean'; default?: unknown; required?: boolean; help?: string; choices?: string[] }

export interface ToolDefinition {
  site: string;
  name: string;
  description: string;
  access: 'read' | 'write';
  strategy?: 'public' | 'cookie' | 'intercept' | 'ui' | 'local';
  domain?: string;
  args?: ArgDef[];
  columns?: string[];
  /** OpenCLI pipeline steps (fetch/map/filter/limit/navigate/click/type/wait/snapshot/evaluate…). */
  pipeline?: unknown[];
  /** JavaScript source of `async (page, args) => …` (browser) or `async (args) => …` (public). */
  func?: string;
  siteSession?: 'ephemeral' | 'persistent';
}

const NAME_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function validateDefinition(def: ToolDefinition): void {
  if (!NAME_RE.test(def.site) || !NAME_RE.test(def.name)) throw Object.assign(new Error('site and name must match /^[a-z0-9][a-z0-9-]{0,63}$/'), { code: 'invalid_definition' });
  if (!def.description) throw Object.assign(new Error('description is required'), { code: 'invalid_definition' });
  if (def.access !== 'read' && def.access !== 'write') throw Object.assign(new Error("access must be 'read' or 'write'"), { code: 'invalid_definition' });
  if (!def.pipeline && !def.func) throw Object.assign(new Error('provide `pipeline` steps or `func` source'), { code: 'invalid_definition' });
  if (def.func && !/^\s*(async\s*)?(\(|[A-Za-z_$])/.test(def.func)) throw Object.assign(new Error('func must be a function expression such as `async (page, args) => { … }`'), { code: 'invalid_definition' });
  if (def.func) {
    // syntax check only — the function is not executed here
    try { new Function(`return (${def.func});`); } catch (err) { throw Object.assign(new Error(`func does not parse: ${(err as Error).message}`), { code: 'invalid_definition' }); }
  }
}

/** Make `@jackwener/opencli/registry` resolvable from the user tools dir via a node_modules symlink. */
export function ensureToolsDir(): string {
  fs.mkdirSync(DEFINED_TOOLS_DIR, { recursive: true });
  const nm = path.join(path.dirname(DEFINED_TOOLS_DIR), 'node_modules', '@jackwener');
  fs.mkdirSync(nm, { recursive: true });
  const link = path.join(nm, 'opencli');
  try {
    const current = fs.existsSync(link) ? fs.realpathSync(link) : null;
    if (current !== fs.realpathSync(opencliRoot)) {
      if (fs.existsSync(link) || fs.lstatSync(link)) fs.rmSync(link, { recursive: true, force: true });
      fs.symlinkSync(opencliRoot, link, 'dir');
    }
  } catch {
    try { fs.rmSync(link, { recursive: true, force: true }); fs.symlinkSync(opencliRoot, link, 'dir'); } catch { /* best effort */ }
  }
  const pkg = path.join(path.dirname(DEFINED_TOOLS_DIR), 'package.json');
  if (!fs.existsSync(pkg)) fs.writeFileSync(pkg, JSON.stringify({ name: 'opencli-mcp-user-tools', private: true, type: 'module' }, null, 2));
  return DEFINED_TOOLS_DIR;
}

export function renderToolModule(def: ToolDefinition): string {
  const funcParams = def.func ? (/^\s*(?:async\s*)?(?:\(([^)]*)\)|([A-Za-z_$][\w$]*))\s*=>/.exec(def.func) ?? /^\s*(?:async\s+)?function\s*[\w$]*\s*\(([^)]*)\)/.exec(def.func)) : null;
  const paramCount = funcParams ? (funcParams[1] ?? funcParams[2] ?? '').split(',').filter((x) => x.trim()).length : 0;
  const browserSteps = def.pipeline?.some((s) => s && typeof s === 'object' && ['navigate', 'click', 'type', 'fill', 'wait', 'press', 'snapshot', 'evaluate', 'intercept', 'tap'].some((k) => k in (s as object)));
  const strategy = (def.strategy ?? (paramCount >= 2 || browserSteps ? 'cookie' : 'public')).toUpperCase();
  const browser = strategy !== 'PUBLIC' && strategy !== 'LOCAL';
  const lines = [
    `// Generated by opencli-mcp tools.define on ${new Date().toISOString()}`,
    `import { cli, Strategy } from '@jackwener/opencli/registry';`,
    ``,
    `cli({`,
    `  site: ${JSON.stringify(def.site)},`,
    `  name: ${JSON.stringify(def.name)},`,
    `  description: ${JSON.stringify(def.description)},`,
    `  access: ${JSON.stringify(def.access)},`,
    def.domain ? `  domain: ${JSON.stringify(def.domain)},` : null,
    `  strategy: Strategy.${strategy},`,
    `  browser: ${browser},`,
    def.siteSession ? `  siteSession: ${JSON.stringify(def.siteSession)},` : null,
    `  args: ${JSON.stringify(def.args ?? [], null, 2).replace(/\n/g, '\n  ')},`,
    def.columns ? `  columns: ${JSON.stringify(def.columns)},` : null,
    def.pipeline ? `  pipeline: ${JSON.stringify(def.pipeline, null, 2).replace(/\n/g, '\n  ')},` : null,
    def.func ? `  func: ${def.func.trim()},` : null,
    `});`,
    ``,
  ].filter((l): l is string => l !== null);
  return lines.join('\n');
}

export async function saveTool(def: ToolDefinition): Promise<{ file: string; site: string; name: string }> {
  validateDefinition(def);
  const dir = path.join(ensureToolsDir(), def.site);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${def.name}.js`);
  fs.writeFileSync(file, renderToolModule(def));
  await import(`${pathToFileURL(file).href}?t=${Date.now()}`);
  return { file, site: def.site, name: def.name };
}

export function deleteTool(site: string, name: string): boolean {
  const file = path.join(DEFINED_TOOLS_DIR, site, `${name}.js`);
  if (!fs.existsSync(file)) return false;
  fs.rmSync(file);
  getRegistry().delete(`${site}/${name}`);
  return true;
}

export function listDefinedTools(): Array<{ site: string; name: string; file: string }> {
  if (!fs.existsSync(DEFINED_TOOLS_DIR)) return [];
  const out: Array<{ site: string; name: string; file: string }> = [];
  for (const site of fs.readdirSync(DEFINED_TOOLS_DIR)) {
    const d = path.join(DEFINED_TOOLS_DIR, site);
    if (!fs.statSync(d).isDirectory()) continue;
    for (const f of fs.readdirSync(d)) if (f.endsWith('.js')) out.push({ site, name: f.replace(/\.js$/, ''), file: path.join(d, f) });
  }
  return out;
}

/**
 * Compile a recorded session trace into a tool draft.
 * Network-first: if the trace captured a JSON endpoint on the site, the tool fetches it through the
 * page (cookies included). Otherwise the UI steps (goto/act/observe) become an explicit function.
 * Values equal to an input are replaced by `args.<input>`.
 */
/** Page-side locator used by compiled tools: tags the best semantic match with data-opencli-compiled. */
function locateJs(spec: { role?: string; name?: string; label?: string; text?: string; testid?: string; nth?: number }): string {
  return `(() => { const spec = ${JSON.stringify(spec)}; const norm = (s) => String(s || '').replace(/\\s+/g, ' ').trim().toLowerCase(); const m = (h, n) => n ? (norm(h) === norm(n) || norm(h).includes(norm(n))) : true;
    const role = (el) => el.getAttribute('role') || ({ a: el.hasAttribute('href') ? 'link' : '', button: 'button', input: ['button','submit'].includes(el.type) ? 'button' : el.type === 'checkbox' ? 'checkbox' : 'textbox', textarea: 'textbox', select: 'combobox' })[el.tagName.toLowerCase()] || '';
    const name = (el) => el.getAttribute('aria-label') || el.getAttribute('placeholder') || el.getAttribute('title') || el.value || el.innerText || el.textContent || '';
    document.querySelectorAll('[data-opencli-compiled]').forEach((n) => n.removeAttribute('data-opencli-compiled'));
    let c = [...document.querySelectorAll('body *')].filter((el) => (!spec.role || role(el) === spec.role) && (!spec.testid || el.getAttribute('data-testid') === spec.testid) && m(name(el), spec.name) && m(name(el), spec.label) && m(el.innerText || el.textContent, spec.text) && el.getClientRects().length);
    c = c.filter((el) => !c.some((o) => o !== el && el.contains(o)));
    const el = c[spec.nth ?? 0]; if (!el) throw new Error('compiled locator found nothing: ' + JSON.stringify(spec)); el.setAttribute('data-opencli-compiled', '1'); return c.length; })()`;
}

export function compileFromTrace(trace: TraceEvent[], opts: { site: string; name: string; description: string; access?: 'read' | 'write'; inputs?: Record<string, string>; domain?: string }): ToolDefinition {
  const inputs = opts.inputs ?? {};
  const argDefs: ArgDef[] = Object.entries(inputs).map(([name, sample]) => ({ name, type: 'string', required: true, help: `example: ${sample}` }));
  const sub = (v: string): string => {
    for (const [k, sample] of Object.entries(inputs)) if (sample && v === sample) return `\${args.${k}}`;
    let out = v;
    for (const [k, sample] of Object.entries(inputs)) if (sample && out.includes(sample)) out = out.split(sample).join(`\${args.${k}}`);
    return out;
  };
  const lit = (v: string): string => { const s = sub(v); return s.includes('${') ? '`' + s.replace(/`/g, '\\`') + '`' : JSON.stringify(s); };

  const net = trace.filter((e): e is Extract<TraceEvent, { kind: 'network' }> => e.kind === 'network' && /json|graphql|x-component/i.test(e.contentType ?? '') && (e.status ?? 200) < 400 && (opts.domain ? e.url.includes(opts.domain) : true));
  const body: string[] = [];
  const firstGoto = trace.find((e): e is Extract<TraceEvent, { kind: 'goto' }> => e.kind === 'goto');
  if (net.length > 0) {
    const best = net.sort((a, b) => (b.bodyBytes ?? 0) - (a.bodyBytes ?? 0))[0];
    if (firstGoto) body.push(`  await page.goto(${lit(firstGoto.url)});`);
    body.push(`  const data = await page.fetchJson(${lit(best.url)}${best.method && best.method !== 'GET' ? `, { method: ${JSON.stringify(best.method)} }` : ''});`);
    body.push(`  return data;`);
  } else {
    for (const e of trace) {
      if (e.kind === 'goto') body.push(`  await page.goto(${lit(e.url)});`);
      else if (e.kind === 'act') {
        // Re-resolve the target the way the agent did: css directly, semantic locators via a page-side query that tags the element.
        const spec = e.targetSpec ?? {};
        let target: string;
        if (spec.css) target = JSON.stringify(spec.css);
        else if (spec.role || spec.name || spec.label || spec.text || spec.testid) { body.push(`  await page.evaluate(${JSON.stringify(locateJs(spec))});`); target = JSON.stringify('[data-opencli-compiled]'); }
        else { body.push(`  // TODO: the agent used a snapshot ref (${e.target}); replace with a stable selector`); target = JSON.stringify(spec.css ?? 'body'); }
        if (e.action === 'click' || e.action === 'dblclick') body.push(`  await page.click(${target});`);
        else if (e.action === 'fill' || e.action === 'type') body.push(`  await page.fillText(${target}, ${lit(String(e.value ?? ''))});`);
        else if (e.action === 'press') body.push(`  await page.pressKey(${JSON.stringify(String(e.value ?? 'Enter'))});`);
        else if (e.action === 'select') body.push(`  await page.evaluate(${JSON.stringify(`(() => { const el = document.querySelector(${target.replace(/"/g, "'")}); if (el) { el.value = ${JSON.stringify(String(e.value ?? ''))}; el.dispatchEvent(new Event('change', { bubbles: true })); } })()`)});`);
        else if (e.action === 'check' || e.action === 'uncheck') body.push(`  await page.setChecked(${target}, ${e.action === 'check'});`);
        body.push(`  await page.wait({ time: 1 });`);
      } else if (e.kind === 'observe') body.push(`  // observed: ${e.mode}${e.summary ? ' — ' + e.summary.slice(0, 80) : ''}`);
    }
    body.push(`  return await page.snapshot({ compact: true, interactive: false });`);
  }
  const func = `async (page, args) => {\n${body.join('\n')}\n}`;
  return { site: opts.site, name: opts.name, description: opts.description, access: opts.access ?? 'read', strategy: 'cookie', domain: opts.domain, args: argDefs, func, siteSession: 'persistent' };
}
