/**
 * tools.define / tools.compile — freeze explored flows into first-class tools.
 * A defined tool is a plain OpenCLI adapter module written to ~/.opencli-mcp/tools/<site>/<name>.js,
 * registered live (tools/list_changed), and reloaded on the next start. Three sources share one
 * registry: built-in adapters, agent-defined tools, page-provided (WebMCP) tools.
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { OPENCLI_MCP_DIR } from '../host/state.js';
import { getRegistry } from '@jackwener/opencli/registry';
import { opencliRoot } from '../lib/opencli.js';
import type { TraceEvent } from '../runtime/trace.js';

/** Where agent-defined tools live. */
export const DEFINED_TOOLS_DIR = path.join(OPENCLI_MCP_DIR, 'tools');

export interface ArgDef { name: string; type?: 'string' | 'int' | 'number' | 'boolean'; default?: unknown; required?: boolean; help?: string; choices?: string[] }

export interface ToolDefinition {
  site: string;
  name: string;
  description: string;
  access: 'read' | 'write';
  strategy?: 'public' | 'cookie' | 'intercept' | 'ui' | 'local';
  domain?: string;
  args?: ArgDef[];
  columns?: string[];
  /** OpenCLI pipeline steps (fetch/map/filter/limit/navigate/click/type/wait/snapshot/evaluate…). */
  pipeline?: unknown[];
  /** JavaScript source of `async ({ tab, args, sites, recon, page }) => …` (frozen flow on the exploration object model) or `async (args) => …` (public, no browser). */
  func?: string;
  siteSession?: 'ephemeral' | 'persistent';
}

const NAME_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function validateDefinition(def: ToolDefinition): void {
  if (!NAME_RE.test(def.site) || !NAME_RE.test(def.name)) throw Object.assign(new Error('site and name must match /^[a-z0-9][a-z0-9-]{0,63}$/'), { code: 'invalid_definition' });
  if (!def.description) throw Object.assign(new Error('description is required'), { code: 'invalid_definition' });
  if (def.access !== 'read' && def.access !== 'write') throw Object.assign(new Error("access must be 'read' or 'write'"), { code: 'invalid_definition' });
  if (!def.pipeline && !def.func) throw Object.assign(new Error('provide `pipeline` steps or `func` source'), { code: 'invalid_definition' });
  if (def.func && !/^\s*(async\s*)?(\(|[A-Za-z_$])/.test(def.func)) throw Object.assign(new Error('func must be a function expression such as `async ({ tab, args }) => { … }`'), { code: 'invalid_definition' });
  if (def.func) {
    // syntax check only — the function is not executed here
    try { new Function(`return (${def.func});`); } catch (err) { throw Object.assign(new Error(`func does not parse: ${(err as Error).message}`), { code: 'invalid_definition' }); }
  }
}

/** Make `@jackwener/opencli/registry` resolvable from the user tools dir via a node_modules symlink. */
export function ensureToolsDir(): string {
  fs.mkdirSync(DEFINED_TOOLS_DIR, { recursive: true });
  const nm = path.join(path.dirname(DEFINED_TOOLS_DIR), 'node_modules', '@jackwener');
  fs.mkdirSync(nm, { recursive: true });
  const link = path.join(nm, 'opencli');
  try {
    const current = fs.existsSync(link) ? fs.realpathSync(link) : null;
    if (current !== fs.realpathSync(opencliRoot)) {
      if (fs.existsSync(link) || fs.lstatSync(link)) fs.rmSync(link, { recursive: true, force: true });
      fs.symlinkSync(opencliRoot, link, 'dir');
    }
  } catch {
    try { fs.rmSync(link, { recursive: true, force: true }); fs.symlinkSync(opencliRoot, link, 'dir'); } catch { /* best effort */ }
  }
  const pkg = path.join(path.dirname(DEFINED_TOOLS_DIR), 'package.json');
  if (!fs.existsSync(pkg)) fs.writeFileSync(pkg, JSON.stringify({ name: 'opencli-mcp-user-tools', private: true, type: 'module' }, null, 2));
  return DEFINED_TOOLS_DIR;
}

export function renderToolModule(def: ToolDefinition): string {
  const funcParams = def.func ? (/^\s*(?:async\s*)?(?:\(([^)]*)\)|([A-Za-z_$][\w$]*))\s*=>/.exec(def.func) ?? /^\s*(?:async\s+)?function\s*[\w$]*\s*\(([^)]*)\)/.exec(def.func)) : null;
  const paramCount = funcParams ? (funcParams[1] ?? funcParams[2] ?? '').split(',').filter((x) => x.trim()).length : 0;
  const browserSteps = def.pipeline?.some((s) => s && typeof s === 'object' && ['navigate', 'click', 'type', 'fill', 'wait', 'press', 'snapshot', 'evaluate', 'intercept', 'tap'].some((k) => k in (s as object)));
  const usesBrowser = Boolean(def.func && /\b(tab|page|sites|recon)\b/.test(def.func));
  const strategy = (def.strategy ?? (paramCount >= 2 || browserSteps || usesBrowser ? 'cookie' : 'public')).toUpperCase();
  const browser = strategy !== 'PUBLIC' && strategy !== 'LOCAL';
  const lines = [
    `// Generated by opencli-mcp tools.define on ${new Date().toISOString()}`,
    `import { cli, Strategy } from '@jackwener/opencli/registry';`,
    ``,
    `cli({`,
    `  site: ${JSON.stringify(def.site)},`,
    `  name: ${JSON.stringify(def.name)},`,
    `  description: ${JSON.stringify(def.description)},`,
    `  access: ${JSON.stringify(def.access)},`,
    def.domain ? `  domain: ${JSON.stringify(def.domain)},` : null,
    `  strategy: Strategy.${strategy},`,
    `  browser: ${browser},`,
    def.siteSession ? `  siteSession: ${JSON.stringify(def.siteSession)},` : null,
    `  args: ${JSON.stringify(def.args ?? [], null, 2).replace(/\n/g, '\n  ')},`,
    def.columns ? `  columns: ${JSON.stringify(def.columns)},` : null,
    def.pipeline ? `  pipeline: ${JSON.stringify(def.pipeline, null, 2).replace(/\n/g, '\n  ')},` : null,
    def.func ? `  func: ${def.func.trim()},` : null,
    `});`,
    ``,
  ].filter((l): l is string => l !== null);
  return lines.join('\n');
}

export async function saveTool(def: ToolDefinition): Promise<{ file: string; site: string; name: string }> {
  validateDefinition(def);
  const dir = path.join(ensureToolsDir(), def.site);
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${def.name}.js`);
  fs.writeFileSync(file, renderToolModule(def));
  await import(`${pathToFileURL(file).href}?t=${Date.now()}`);
  return { file, site: def.site, name: def.name };
}

export function deleteTool(site: string, name: string): boolean {
  const file = path.join(DEFINED_TOOLS_DIR, site, `${name}.js`);
  if (!fs.existsSync(file)) return false;
  fs.rmSync(file);
  getRegistry().delete(`${site}/${name}`);
  return true;
}

export function listDefinedTools(): Array<{ site: string; name: string; file: string }> {
  if (!fs.existsSync(DEFINED_TOOLS_DIR)) return [];
  const out: Array<{ site: string; name: string; file: string }> = [];
  for (const site of fs.readdirSync(DEFINED_TOOLS_DIR)) {
    const d = path.join(DEFINED_TOOLS_DIR, site);
    if (!fs.statSync(d).isDirectory()) continue;
    for (const f of fs.readdirSync(d)) if (f.endsWith('.js')) out.push({ site, name: f.replace(/\.js$/, ''), file: path.join(d, f) });
  }
  return out;
}

/**
 * Compile a recorded session trace into a tool draft.
 * Network-first: if the trace captured a JSON endpoint on the site, the tool fetches it through the
 * page (cookies included). Otherwise the UI steps (goto/act/observe) become an explicit function.
 * Values equal to an input are replaced by `args.<input>`.
 */
/** `mode` is the agent's explicit declaration of where the sample may be replaced: 'exact' (default) only whole literals equal to the sample; 'within' also inside longer literals (typed values, expectation texts/urls). */
export type CompileInput = string | { sample: string; description?: string; type?: 'string' | 'int' | 'number' | 'boolean'; required?: boolean; mode?: 'exact' | 'within' };

/**
 * Compile a recorded session trace into a tool draft.
 * Network-first: if the trace captured a JSON endpoint on the site, the tool fetches it through the page (cookies
 * included). Otherwise the UI steps become an explicit function on the same engine the agent used: `page.act` with the
 * replay selector recorded at act time, `page.expect` checkpoints where the agent asserted the page, and a structured
 * failure (`step`, `label`, `state`) when a step fails. Inputs are explicit: only exact occurrences of a declared
 * sample value become `args.<name>`.
 */
function hostOf(url: string): string | undefined { try { return new URL(url).hostname.replace(/^www\./, ''); } catch { return undefined; } }
const NOISE = /(googletagmanager|google-analytics|doubleclick|facebook\.net|hotjar|sentry|segment\.com|intercom|crazyegg|clarity\.ms|cloudflareinsights|hcaptcha|recaptcha|amazon-adsystem|newrelic|datadoghq|\/collect\b|\/beacon\b|\/telemetry\b|\/analytics\b|\/log\b)/i;
/** Words worth matching: what the agent saw (observe state) or extracted (evaluate result) — long enough to be specific. */
function evidenceTokens(trace: TraceEvent[]): Set<string> {
  const texts: string[] = [];
  for (const e of trace) {
    if (e.kind === 'evaluate' && e.result) texts.push(e.result);
    if (e.kind === 'observe' && e.sample) texts.push(e.sample.replace(/\[ref=e\d+\]/g, ''));
  }
  const out = new Set<string>();
  for (const t of texts.slice(-4)) for (const w of t.match(/[\p{L}\p{N}][\p{L}\p{N}'’.-]{3,}/gu) ?? []) if (!/^(true|false|null|undefined|button|link|heading|text|list|listitem|navigation|generic|main|banner|contentinfo|complementary|region|article|image|img|textbox|combobox|checkbox|https?)$/i.test(w)) out.add(w.toLowerCase());
  return out;
}
/** The captured JSON response that carries the data the agent ended up with; else the largest same-site JSON response. */
function pickEndpoint(trace: TraceEvent[], host: string | undefined): { endpoint: Extract<TraceEvent, { kind: 'network' }>; matched: number; byDefault: boolean } | null {
  const cands = trace.filter((e): e is Extract<TraceEvent, { kind: 'network' }> => e.kind === 'network' && /json|graphql|x-component/i.test(e.contentType ?? '') && (e.status ?? 200) < 400 && (e.resourceType === undefined || e.resourceType === 'XHR' || e.resourceType === 'Fetch') && !NOISE.test(e.url) && (!host || (hostOf(e.url) ?? '').endsWith(host)));
  if (!cands.length) return null;
  const tokens = evidenceTokens(trace);
  let best: { endpoint: typeof cands[number]; matched: number } | null = null;
  for (const c of cands) {
    if (!c.responseSample || !tokens.size) continue;
    const hay = c.responseSample.toLowerCase();
    let matched = 0; for (const t of tokens) if (hay.includes(t)) matched++;
    if (matched && (!best || matched > best.matched || (matched === best.matched && (c.bodyBytes ?? 0) > (best.endpoint.bodyBytes ?? 0)))) best = { endpoint: c, matched };
  }
  if (best) return { ...best, byDefault: false };
  const largest = [...cands].sort((a, b) => (b.bodyBytes ?? 0) - (a.bodyBytes ?? 0))[0];
  return { endpoint: largest, matched: 0, byDefault: true };
}
/** URL literal with query values equal to an input sample replaced by the (encoded) argument. */
function urlLit(url: string, inputs: Array<{ name: string; sample: string; mode: 'exact' | 'within' }>, lit: (v: string) => string): string {
  try {
    const u = new URL(url); let touched = false;
    for (const [k, v] of [...u.searchParams]) for (const i of inputs) if (i.sample && (v === i.sample || (i.mode === 'within' && v.includes(i.sample)))) { u.searchParams.set(k, `__ARG_${i.name}__${v === i.sample ? '' : v.split(i.sample).join(`__ARG_${i.name}__`)}`); touched = true; }
    if (!touched) return lit(url);
    const s = u.toString().replace(/__ARG_([a-zA-Z_$][\w$]*)__/g, (_m, n: string) => `\${encodeURIComponent(args.${n})}`);
    return '`' + s.replace(/`/g, '\\`') + '`';
  } catch { return lit(url); }
}
/** Body literal: JSON string values equal to an input sample become the argument (correctly escaped via JSON.stringify); form bodies go through URLSearchParams; anything else stays a literal. */
function bodyLit(post: string, contentType: string | undefined, inputs: Array<{ name: string; sample: string; mode: 'exact' | 'within' }>, lit: (v: string) => string): string {
  const mark = (v: string): string | null => { for (const i of inputs) { if (!i.sample) continue; if (v === i.sample) return `__ARG_${i.name}__`; if (i.mode === 'within' && v.includes(i.sample)) return v.split(i.sample).join(`__ARG_${i.name}__`); } return null; };
  const unmark = (s: string): string => s.replace(/"((?:[^"\\]|\\.)*__ARG_[a-zA-Z_$][\w$]*__(?:[^"\\]|\\.)*)"/g, (_m, inner: string) => /^__ARG_[a-zA-Z_$][\w$]*__$/.test(inner) ? `args.${inner.slice(6, -2)}` : '`' + inner.replace(/__ARG_([a-zA-Z_$][\w$]*)__/g, '${args.$1}') + '`');
  try {
    const walk = (v: unknown): unknown => { if (typeof v === 'string') return mark(v) ?? v; if (Array.isArray(v)) return v.map(walk); if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v as Record<string, unknown>).map(([k, x]) => [k, walk(x)])); return v; };
    const json = JSON.parse(post) as unknown;
    const marked = JSON.stringify(walk(json));
    return marked.includes('__ARG_') ? `JSON.stringify(${unmark(marked)})` : `JSON.stringify(${marked})`;
  } catch { /* not JSON */ }
  if (/x-www-form-urlencoded/i.test(contentType ?? '')) {
    const p = new URLSearchParams(post); let touched = false;
    for (const [k, v] of [...p]) { const m = mark(v); if (m) { p.set(k, m); touched = true; } }
    if (touched) return '`' + p.toString().replace(/__ARG_([a-zA-Z_$][\w$]*)__/g, '${encodeURIComponent(args.$1)}').replace(/`/g, '\\`') + '`';
  }
  return lit(post);
}

export function compileFromTrace(trace: TraceEvent[], opts: { site: string; name: string; description: string; access?: 'read' | 'write'; inputs?: Record<string, CompileInput>; domain?: string }): ToolDefinition & { warnings?: string[] } {
  const inputs = Object.entries(opts.inputs ?? {}).map(([name, v]) => (typeof v === 'string' ? { name, sample: v, type: 'string' as const, required: true, mode: 'exact' as const } : { name, sample: v.sample, type: v.type ?? 'string', required: v.required ?? true, help: v.description, mode: v.mode ?? 'exact' as const }));
  const argDefs: ArgDef[] = inputs.map((i) => ({ name: i.name, type: i.type, required: i.required, help: i.help ?? `example: ${i.sample}` }));
  // exact by default: a literal becomes an argument only when it IS the sample; 'within' inputs are the agent's explicit
  // permission to also parameterize longer literals that contain the sample (values typed, checkpoint texts and urls)
  const sub = (v: string): string => {
    for (const i of inputs) if (i.sample && v === i.sample) return `\${args.${i.name}}`;
    let out = v;
    for (const i of inputs) if (i.mode === 'within' && i.sample && out.includes(i.sample)) out = out.split(i.sample).join(`\${args.${i.name}}`);
    return out;
  };
  const lit = (v: string): string => { const s = sub(v); return s.includes('${') ? '`' + s.replace(/`/g, '\\`') + '`' : JSON.stringify(s); };

  const body: string[] = [];
  const warnings: string[] = [];
  const firstGoto = trace.find((e): e is Extract<TraceEvent, { kind: 'goto' }> => e.kind === 'goto');
  const best = pickEndpoint(trace, opts.domain ?? (firstGoto ? hostOf(firstGoto.url) : undefined));
  if (best) {
    const { endpoint: e, matched, byDefault } = best;
    if (firstGoto) body.push(`  await tab.goto(${lit(firstGoto.url)});`);
    // freeze the whole call the page made, not a guessed URL: method, the request headers that are part of the
    // contract (x-*, content-type, accept…), the body — with the declared inputs parameterized where they occurred
    const init: string[] = [];
    if (e.method && e.method !== 'GET') init.push(`method: ${JSON.stringify(e.method)}`);
    const headers = Object.fromEntries(Object.entries(e.requestHeaders ?? {}).filter(([k]) => /^(content-type|accept|x-.*|apikey|api-key|client-id)$/i.test(k)));
    if (Object.keys(headers).length) init.push(`headers: ${JSON.stringify(headers)}`);
    if (e.postData) init.push(`body: ${bodyLit(e.postData, e.requestHeaders?.['content-type'], inputs, lit)}`);
    body.push(`  const data = await tab.fetchJson(${urlLit(e.url, inputs, lit)}${init.length ? `, { ${init.join(', ')} }` : ''});`);
    body.push(`  return data;`);
    if (e.auth) warnings.push(`the captured request carried an Authorization header, which is not frozen (it is a credential the page computes); the tool will fail unless the endpoint also accepts the cookie session — prefer a cookie-authenticated endpoint or read the header from the page at run time`);
    if (byDefault) warnings.push(`endpoint ${e.method ?? 'GET'} ${e.url.slice(0, 120)} was chosen by size, not by matching the data you extracted (no observe/evaluate evidence found in it); verify with tab.fetchJson before defining`);
    else warnings.push(`endpoint ${e.method ?? 'GET'} ${e.url.slice(0, 120)} matched ${matched} word(s) of the data you extracted`);
  } else {
    if (trace.some((e) => e.kind === 'network')) warnings.push('no JSON endpoint carried the data you extracted — the tool is frozen as UI steps (DOM); read tab.network.read() and recon.discover(tab) for an API, verify it with tab.fetchJson, then compile again');
    else warnings.push('the trace has no captured requests (capture starts when a session tab is attached; adapter tabs do not capture) — the tool is frozen as UI steps (DOM)');
    // every step is wrapped so a failure names the step, carries the engine's error code/hint and the page state at that moment
    body.push(`  const step = async (n, label, fn) => { try { return await fn(); } catch (e) { const state = await tab.observe({ diff: false, viewport: true }).then((o) => o.state || '').catch(() => ''); throw Object.assign(new Error('step ' + n + ' (' + label + ') failed: ' + (e && e.message || e)), { code: (e && e.code) || 'step_failed', hint: e && e.hint, step: n, label, state: String(state).slice(0, 4000), expect: e && e.data && e.data.expect, failed: e && e.data && e.data.failed }); } };`);
    let n = 0;
    const push = (label: string, call: string) => { n += 1; body.push(`  await step(${n}, ${JSON.stringify(label)}, () => ${call});`); };
    for (const e of trace) {
      if (e.kind === 'goto') push(`goto ${e.url.slice(0, 60)}`, `tab.goto(${lit(e.url)})`);
      else if (e.kind === 'act') {
        if (!e.ok) continue;
        const spec = (e.targetSpec ?? {}) as Record<string, unknown>;
        const { frame, ...loc } = spec;
        // freeze the intent the agent expressed (role/name, label, text, testid, a selector it chose, within), not the element the
        // engine happened to resolve it to: intent survives a redesign, the resolved selector does not. Only a one-time ref or
        // a point has no intent to keep — then the engine's replay selector is frozen and the tool is flagged for review.
        const intent = ['role', 'name', 'label', 'text', 'testid', 'selector', 'within'].some((k) => k in loc);
        const target: Record<string, unknown> = intent ? { ...loc } : e.targetSelector ? { selector: e.targetSelector } : { ...loc };
        if (frame !== undefined) target.frame = frame;
        const structural = (s: unknown) => typeof s === 'string' && !s.startsWith('internal:') && !/^#[\w-]+$|\[data-testid=|\[data-[\w-]+=|^aria-ref=/.test(s) && !s.includes(' >> internal:');
        if (!intent) {
          const why = typeof loc.ref === 'string' ? `aria ref ${loc.ref} (one-time)` : 'a viewport point';
          warnings.push(`step ${n + 1}: acted on ${why}; frozen as the engine's replay selector ${JSON.stringify(e.targetSelector ?? null)} — replace with a stable locator (testid, role+name, label, or a selector scoped by within)`);
          body.push(`  // REVIEW: acted on ${why} — the replay selector below is what the engine resolved at exploration time, not an intent`);
        } else if (structural(loc.selector)) warnings.push(`step ${n + 1}: selector ${JSON.stringify(loc.selector)} is structural css; it breaks on a redesign — prefer testid, role+name or label`);
        const valued = ['fill', 'type', 'press', 'select'].includes(e.action);
        push(`${e.action} ${e.target}`.slice(0, 80), `tab.act({ action: ${JSON.stringify(e.action)}, target: ${JSON.stringify(target)}${valued ? `, value: ${lit(String(e.value ?? (e.action === 'press' ? 'Enter' : '')))}` : ''} })`);
      } else if (e.kind === 'expect') {
        if (!e.ok) continue;
        const what = Object.fromEntries(Object.entries(e.what).map(([k, v]) => [k, typeof v === 'string' ? sub(v) : v]));
        const parameterized = Object.entries(what).filter(([, v]) => typeof v === 'string' && v.includes('${args.')).map(([k]) => k);
        if (parameterized.length) body.push(`  // checkpoint ${parameterized.join('/')} follows the input (declared mode "within"); it checks the page reflects the argument, not a fixed value`);
        const literal = JSON.stringify(what).replace(/"\$\{args\.([a-zA-Z_$][\w$]*)\}"/g, 'args.$1').replace(/"([^"]*\$\{args\.[^"]*)"/g, (_m, inner: string) => '`' + inner.replace(/`/g, '\\`') + '`');
        push(`expect ${Object.keys(e.what).join(',')}`, `tab.expect(${literal})`);
      } else if (e.kind === 'observe') body.push(`  // observed: ${e.mode}${e.summary ? ' — ' + e.summary.slice(0, 80) : ''}`);
    }
    body.push(`  return await tab.observe({ diff: false });`);
  }
  const func = `async ({ tab, args }) => {\n${body.join('\n')}\n}`;
  return { site: opts.site, name: opts.name, description: opts.description, access: opts.access ?? 'read', strategy: 'cookie', domain: opts.domain, args: argDefs, func, siteSession: 'persistent', ...(warnings.length && { warnings }) };
}
